using E_Commerce_Website_System05.Models;
using System.Linq;
namespace E_Commerce_Website_System05
{
    internal class Program
    {
        public static ECommerceContext context = new ECommerceContext();

        // 01 Register a New User
        public static void RegisterUser()
        {
            //int userId = context.Users.Count + 1;

            Console.WriteLine("Enter your username");
            string username = Console.ReadLine();

            Console.WriteLine("Enter your email");
            string email = Console.ReadLine();

            Console.WriteLine("Enter your password");
            string passwordHash = Console.ReadLine(); 

            Console.WriteLine("Enter your fullName");
            string fullName = Console.ReadLine();

            Console.WriteLine("Enter your address");
            string address = Console.ReadLine();

            context.Users.Add(new Models.User
            {
                //id generated by SQL server 
                username= username,
                email= email,
                passwordHash= passwordHash,
                fullName= fullName,
                address= address,
                registrationDate= DateTime.Now,
                isActive=true
            });
            context.SaveChanges();
            User assignedUserId = context.Users.OrderBy(u => u.userId).Last();
            Console.WriteLine("User registered successfully. Assigned ID: "+ assignedUserId.userId);

        }
        
        //02 Add a New Product to a Category

        //need to add category first
        public static void AddCategory(){
            Console.WriteLine("Enter  category Name");
            string categoryName = Console.ReadLine();

            Console.WriteLine("Enter  description for the catogory (optional) ");
            string description = Console.ReadLine();

            Console.WriteLine("Enter  imageUrl (optional) ");
            string imageUrl = Console.ReadLine();

            context.Categories.Add(new Category
            {
                categoryName= categoryName,
                description= description,
                imageUrl= imageUrl
            });
            context.SaveChanges();

            Category assignedCategoryId = context.Categories.OrderBy(u => u.categoryId).Last();

            Console.WriteLine("Category registered successfully. Assigned ID: " + assignedCategoryId.categoryId);

        }

        //dispaly all Categories so user can choose from list
        public static void ViewAllCategories()
        {
            Console.WriteLine("=== All Categories ===");
            foreach (Category c in context.Categories)
            {
                Console.WriteLine("CategoryId : "+c.categoryId+ " / category Name : "+c.categoryName);
            }
        }

        public static void AddProduct()
        {
            Console.WriteLine("Enter categoryId that you to add prodict to that category");
            int enteredCategoryId = int.Parse(Console.ReadLine());

            Category selectedCategory = context.Categories.FirstOrDefault(c => c.categoryId == enteredCategoryId);

            if (selectedCategory == null)
            {
                Console.WriteLine("no Category found with id");
                return;
            }

            //add product
            Console.WriteLine("Enter product Name");
            string productName = Console.ReadLine();

            Console.WriteLine("Enter description (optional)");
            string description = Console.ReadLine();

            Console.WriteLine("Enter product's price");
            decimal price = decimal.Parse(Console.ReadLine());

            Console.WriteLine("Enter product's stock Quantity");
            int stockQuantity = int.Parse(Console.ReadLine());

            Console.WriteLine("Enter imageUrl (optional)");
            string imageUrl = Console.ReadLine();

            Product product = new Product
            {
                productName= productName,
                description= description,
                price= price,
                stockQuantity= stockQuantity,
                imageUrl= imageUrl,
                createdAt=DateTime.Now,
                isAvailable=true
            };

            context.SaveChanges();

            
            Console.WriteLine("Product Added successfully. Assigned ID: " + product.productId);

        }

        //03 Place an Order
        public static void PlaceOrder()
        {

           
            Console.Write("Enter user ID: ");
            int userId = int.Parse(Console.ReadLine());

            User enteredUser = context.Users.FirstOrDefault(u => u.userId == userId); 
            if (enteredUser == null)
            {
                Console.WriteLine("Invalid user ID.");
                return;
            }

            Console.WriteLine("Enter  your shipping Address");
            string shippingAddress = Console.ReadLine();

            Console.WriteLine("Enter payment Method (Visa - Cash )");
            string paymentMethod = Console.ReadLine();

            //create order
            Order order = new Order
            {
                userId = userId,
                orderDate =DateTime.Now,
                status= "Pending",
                totalAmount = 0,
                shippingAddress = shippingAddress,
                paymentMethod= paymentMethod

            };

            context.SaveChanges();

       
            Console.WriteLine(" Order record successfully place it . Assigned ID: " + order.orderId);

            //display all available products
            List<Product> availableProducts = context.Products.Where(p => p.isAvailable == true).ToList();
            foreach(Product p in availableProducts)
            {
                Console.WriteLine("productId : " + p.productId);
                Console.WriteLine("productName : " + p.productName);
                Console.WriteLine("price : " + p.price);
                Console.WriteLine("stockQuantity : " + p.stockQuantity);
            }

            decimal total = 0;
            while (true)
            {
                Console.WriteLine("Enter productId");
                int enteredProductId = int.Parse(Console.ReadLine());

                Product selectedProductId = context.Products.FirstOrDefault(p => p.productId == enteredProductId);
                if (selectedProductId == null)
                {
                    Console.WriteLine("Invalid or unavailable product.");
                    return;
                }

                Console.WriteLine("Enter quantity");
                int quantity = int.Parse(Console.ReadLine());

                if (quantity > selectedProductId.stockQuantity)
                {
                    Console.WriteLine("Not enough stock.");
                    continue;
                }

                context.OrderItems.Add(new OrderItem
                {
                    productId = selectedProductId.productId,
                    quantity = quantity,
                    orderId = order.orderId,
                    unitPrice = selectedProductId.price

                });

                total += selectedProductId.price * quantity;

                int decrementStockQuantity = selectedProductId.stockQuantity - quantity;
               


                Console.WriteLine("Add another product? (Y/N)");
                string answer = Console.ReadLine();

                if (answer.ToUpper() != "Y")
                    break;

            }

            order.totalAmount = total;
            context.SaveChanges();
        }

        // 04 Write a Product Review
        public static void AddReview()
        {
            //display available users
            Console.WriteLine("=== Available Users ===");
            foreach(User u in context.Users)
            {
                Console.WriteLine("userId : "+u.userId+ " / fullName : "+u.fullName);
            }

            Console.WriteLine("Enter user ID");
            int enteredUserId = int.Parse(Console.ReadLine());

            User selectedUser = context.Users.FirstOrDefault(u => u.userId == enteredUserId);

            if (selectedUser == null)
            {
                Console.WriteLine("Invlid UserId");
                return;
            }
            //dispaly available products
            Console.WriteLine("=== Available Products ===");
            foreach (Product u in context.Products)
            {
                Console.WriteLine("productId : " + u.productId + " / productName : " + u.productName);
            }

            Console.WriteLine("Enter product ID");
            int enteredproductId = int.Parse(Console.ReadLine());

            Product selectedProduct = context.Products.FirstOrDefault(u => u.productId == enteredproductId);

            if (selectedProduct == null)
            {
                Console.WriteLine("Invlid product Id");
                return;
            }
            //create the review
            Console.WriteLine("Enter your rate (1-5)");
            int rating = int.Parse(Console.ReadLine());

            Console.WriteLine("Enter your comment (optional)");
            string comment = Console.ReadLine();

            Review review = new Review {
                userId= selectedUser.userId,
                productId= selectedProduct.productId,
                rating = rating,
                comment= comment,
                reviewDate=DateTime.Now
            };
            context.Reviews.Add(review);
            context.SaveChanges();
            Console.WriteLine("Review Added successfully. Assigned ID: "+review.reviewId);

        }

        //05 Update Product Price and Availability
        public static void UpdateProduct()
        {
            Console.WriteLine("== Available products ===");

            List<Product> availableProducts = context.Products.Where(p => p.isAvailable == true).ToList();

            foreach(Product p in context.Products)
            {
                Console.WriteLine("productId : "+p.productId+ " / productName : "+ p.productName+ " / price : " + p.price+ " / isAvailable : "+p.isAvailable);
            }

            Console.WriteLine("Enter productId that you want to update Price and Availability");
            int enteredProductId = int.Parse(Console.ReadLine());

            Product selectedProduct = context.Products.FirstOrDefault(p => p.productId == enteredProductId);

            if (selectedProduct == null)
            {
                Console.WriteLine("Invalid productId");
                return;
            }
            selectedProduct.price = 300;
            selectedProduct.isAvailable = false;
            context.SaveChanges();
            Console.WriteLine("Price and Availability are updated");

        }

        //06 Cancel an Order
        public static void CancelOrder()
        {
            List<Order> displayOrders = context.Orders.Where(o => o.status != "Cancelled").ToList();

            foreach ( Order x  in displayOrders)
            {
                Console.WriteLine("orderId : "+x.orderId);
                Console.WriteLine("status : " + x.status);
                Console.WriteLine("shippingAddress : " + x.shippingAddress);
            }

            Console.WriteLine("Enter orderId to cancelled order");
            int enteredOrderId = int.Parse(Console.ReadLine());

            Order selectedOrderId = context.Orders.FirstOrDefault(a => a.orderId == enteredOrderId);

            if (selectedOrderId == null)
            {
                Console.WriteLine("invalid order ID");
                return;
            }
            //Load all OrderItems for that order 
            List<OrderItem> displayOrderItems = context.OrderItems.Where(a => a.orderId == enteredOrderId).ToList();

            foreach(OrderItem a in displayOrderItems)
            {
                Console.WriteLine("orderId :"+a.orderId);
                Console.WriteLine("orderItemId :" + a.orderItemId);
                Console.WriteLine("quantity :" + a.quantity);

                Product product = context.Products.FirstOrDefault(p => p.productId == a.productId);

                product.stockQuantity = product.stockQuantity + a.quantity;

            }
            selectedOrderId.status = "Cancelled";
            context.SaveChanges();





        }


        //07 Delete a Review



        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
        }
    }
}
